### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sampling_synchronization'

### ISSUE THREAD

**Issue by Adentrotter** [git-artes/gr-tempest#4]
Hello,
Thanks for this project.
I managed to install it on Ubuntu.
File "/home/user/gr-tempest/build/gr-tempest/examples/semi_automatic_tempest_example.py", line 116, in __init__
    self.tempest_sampling_synchronization_0 = tempest.sampling_synchronization(interpolatedHsize, epsilon)
AttributeError: 'module' object has no attribute 'sampling_synchronization'

I get this error, any idea?
Thanks

**Comment by git-artes** [comment]
Hi,
Did you disable the File Sink and the Throttle? You may attach a screenshot of the flowgraph if that doesn't work.
Best

**Comment by git-artes** [comment]
Hi, 
Please open different issues for different problems. If you solved them by yourself you may post the answer.
Regarding this question, it's on the FAQ. You probably have not installed swig. See the FAQ for further instructions.
Best

**Comment by MarcosRamo** [comment]
> Hello, Thanks for this project. I managed to install it on Ubuntu. File "/home/user/gr-tempest/build/gr-tempest/examples/semi_automatic_tempest_example.py", line 116, in **init** self.tempest_sampling_synchronization_0 = tempest.sampling_synchronization(interpolatedHsize, epsilon) AttributeError: 'module' object has no attribute 'sampling_synchronization'
> 
> I get this error, any idea? Thanks

I was having the same trouble here and I fixed by this way bellow:
When you run executes the flow graph on GNURADIO, he generates first of all the .py file of the flow graph on your specific folder
![image](https://github.com/git-artes/gr-tempest/assets/84459831/a6afc316-00d0-436e-a8c1-3fb2ec9281e1)

But analyzing the python code generated I found out that there is an "import of tempest" (I don't know the reason), after the import of tempest from gnuradio
![image](https://github.com/git-artes/gr-tempest/assets/84459831/9cb5aff0-a15e-4d74-8225-7b941cd9bea3)

I fixed just deleting the import "import tempest". But in this case you need to run the code after on terminal using the command "python3 <name_of_file.py>, because if you try to run on GnuRadio again, he going rewrite the file with the incorrect import again and it probably gonna fail again.

I hope can helped you!
